apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause-pods
  namespace: default
spec:
  replicas: 150
  selector:
    matchLabels:
      run: pause-pods
  template:
    metadata:
      labels:
        run: pause-pods
    spec:
      containers:
      - name: reserve-resources
        image: k8s.gcr.io/pause