version: 2

updates:
  - package-ecosystem: pip
    directory: "/helm"
    schedule:
      interval: monthly
  - package-ecosystem: "terraform" 
    directory: "/terraform" 
    schedule:
      interval: "weekly"