version: 2

updates:
  - package-ecosystem: pip
    directory: "/helm"
    schedule:
      interval: monthly
  - package-ecosystem: "terraform" 
    directory: "/terraform/local" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform" 
    directory: "/terraform/modules/cluster" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform" 
    directory: "/terraform/modules/ide" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform" 
    directory: "/terraform/modules/addons/descheduler" 
    schedule:
      interval: "weekly"
