apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # HIGHLIGHT
  name: apps
  namespace: argocd
  # HIGHLIGHT
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # HIGHLIGHT
    repoURL: ${GITOPS_REPO_URL}
    # HIGHLIGHT
    targetRevision: main
    # HIGHLIGHT
    path: apps-config
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
