apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: aiml
spec:
  labels:
    type: karpenter
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: "karpenter.k8s.aws/instance-family"
      operator: In
      values: [inf1]
  providerRef:
    name: aiml
  ttlSecondsAfterEmpty: 30

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: aiml
spec:
  subnetSelector:
    aws-ids: ${AIML_SUBNETS}
  securityGroupSelector:
    karpenter.sh/discovery: ${EKS_CLUSTER_NAME}
  # Increase the ephemeral storage for hosting a large Deep Learning Container
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        deleteOnTermination: true
  tags:
    app.kubernetes.io/created-by: eks-workshop