apiVersion: v1
data:
  mapAccounts: |
    []
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::953135736012:role/eks-workshop-cluster-managed-ondemand
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::953135736012:role/eks-workshop-cluster-managed-system
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::953135736012:role/eks-workshop-cluster-role
      username: eks-workshop-cluster-role
    - groups:
      - systems:masters
      rolearn: arn:aws:iam::953135736012:role/Admin
      username: eks-workshop-cluster-role
  mapUsers: |
    - groups:
      - systems:masters
      userarn: arn:aws:iam::953135736012:user/cluster-admin
immutable: false
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/created-by: terraform-aws-eks-blueprints
    app.kubernetes.io/managed-by: terraform-aws-eks-blueprints
  name: aws-auth
  namespace: kube-system
