apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: terraform
    http:
      url: https://releases.hashicorp.com/terraform/1.1.8/terraform_1.1.8_linux_amd64.zip
  - path: kubectl
    githubRelease:
      slug: kubernetes/kubernetes
      tagSelection:
        semver:
          constraints: ">= 1.23.0 < 1.24.0"
      http:
        url: https://dl.k8s.io/release/{tag}/bin/linux/amd64/kubectl
  - path: helm
    githubRelease:
      slug: helm/helm
      tagSelection:
        semver:
          constraints: ">= 3.8.0 < 4.0.0"
      http:
        url: https://get.helm.sh/helm-{tag}-linux-amd64.tar.gz