apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
spec:
  template:
    spec:
      containers:
        - name: carts
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /test-pd
              name: test-volume
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
        - name: test-volume
          hostPath:
            path: /etc
            type: Directory
