apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: $(EKS_CLUSTER_NAME)-catalog-crossplane
spec:
  forProvider:
    region: $(AWS_DEFAULT_REGION)
    description: SecurityGroup
    groupName: $(EKS_CLUSTER_NAME)-catalog-crossplane
    vpcId: $(VPC_ID)
    ingress:
      - fromPort: 3306
        toPort: 3306
        ipProtocol: tcp
        ipRanges:
          - cidrIp: "0.0.0.0/0"
    egress:
      # AWS will treat it as all ports any protocol
      - ipProtocol: '-1'
        ipRanges:
          - cidrIp: "0.0.0.0/0"
  providerConfigRef:
    name: aws-provider-config
