apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # HIGHLIGHT
  name: checkout
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    # HIGHLIGHT
    path: apps-kustomization/checkout
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
