apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # HIGHLIGHT
  name: apps
  namespace: argocd
spec:
  project: default
  # HIGHLIGHT
  source:
    repoURL: ${REPO_URL}
    targetRevision: main
    # HIGHLIGHT
    path: apps
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
