apiVersion: iam.services.k8s.aws/v1alpha1
kind: Policy
metadata:
  name: ack-mq-controller
  namespace: ack-system
spec:
  description: Policy for ACK MQ controller deployment on EKS cluster using Helm charts
  name: ack-mq-controller
  policyDocument: >
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": "ec2:ModifyNetworkInterfaceAttribute",
          "Resource": "*"
        }
      ]
    }
---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: ack-mq-controller
  namespace: ack-system
spec:
  description: IRSA role for ACK MQ controller deployment on EKS cluster using Helm charts
  name: ack-mq-controller
  policies:
    - "arn:aws:iam::aws:policy/AmazonMQFullAccess"
    - "arn:aws:iam::015299085168:policy/ack-mq-controller"
  assumeRolePolicyDocument: >
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Federated": "arn:aws:iam::015299085168:oidc-provider/"
          },
          "Action": "sts:AssumeRoleWithWebIdentity",
          "Condition": {
            "StringEquals": {
              ":sub": "system:serviceaccount:ack-system:ack-mq-controller"
            }
          }
        }
      ]
    }
