apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: checkoutv2
resources:
  - ../../../../base-application/checkout
patches:
  - deploymentv2.yaml
  - servicev2.yaml
  - delete-deployment-redis.yaml
  - delete-service-redis.yaml
