apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-privileged
spec:
  template:
    spec:
      containers:
      - name: ubuntu-privileged
        volumeMounts:
        - mountPath: /test-pd
          name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          path: /etc
          type: Directory

