name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  verify-helm-charts:
    name: verify-helm-charts
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Verify helm chart yaml
      run: |
        make verify-helm-metadata