name: Publish Preview

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Install hugo
      run: |
        sudo apt-get update
        sudo apt-get install -y curl git

        curl -L https://github.com/gohugoio/hugo/releases/download/v0.91.2/hugo_0.91.2_Linux-64bit.deb -o hugo.deb

        sudo apt install ./hugo.deb
    - name: Generate site
      working-directory: site
      run: hugo
    - name: Get AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.6.1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: GithubActionsSession
    - name: Sync
      working-directory: site/public
      run: aws sync . s3://${{ secrets.PREVIEW_CONTENT_S3_BUCKET }}
