name: Test - Security

on:
  workflow_dispatch:
  schedule:
  - cron: '0 7 * * 4'

permissions:
  id-token: write
  contents: read

jobs:
  test-module:
    uses: ./.github/workflows/module-test.yml
    with:
      module: security
    secrets: inherit