name: Test - Automation

on:
  workflow_dispatch:
  schedule:
  - cron: '0 7 * * 5'

permissions:
  id-token: write
  contents: read

jobs:
  test-module:
    uses: ./.github/workflows/module-test.yml
    with:
      module: automation
    secrets: inherit